### ISSUE TITLE
Formatting?

### ISSUE THREAD

**Issue by MattFoley** [stefalda/ReactNativeLocalization#10]
As far as I can tell, this library does not yet support formatting localization. Do plan to support that?

ie: `format(strings['This is a {$1} dog'], strings['big'])` should return `This is a big dog` for `en`, but  `Este es un perro grande` for `es`

It's something I'm sorely missing in React Native so far, with the React integration of Format.js not yet supporting React Native.

**Comment by stefalda** [comment]
Currently there is no native method, but it could be easily added like this:

```javascript
  function stringFormat(str, ...values){
        var res = str;
        for (let i=0; i<values.length;i++){
            res = res.replace("{"+i+"}", values[i]);
        }
        return res;
    }
```

then you could have

```javascript
var strings = new  LocalizedStrings({
  "en":{
    what:"This is a {0} dog",
    sizeBig:"big"
  },
  "es":{
    what:"Este es un perro {0}",
    sizeBig:"grande"
  }
});

var value = stringFormat(strings.what, strings.sizeBig);
```

Could it work?

**Comment by stefalda** [comment]
I've added a formatString method based on the above suggestions...
