### ISSUE TITLE
XCode semantic issue

### ISSUE THREAD

**Issue by menderleit** [stefalda/ReactNativeLocalization#100]
I get a build error in XCode after I upgraded to ReactNative v0.49.3.

`
ReactNativeLocalization Group
Semantic Issue Group
/vagrant/FLEX-mobile/node_modules/react-native/React/Base/RCTBridgeModule.h:52:1: Unknown type name 'RCT_EXTERN_C_BEGIN'
/vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.m:24:9: In file included from /vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.m:24:
/vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.h:27:9: In file included from /vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.h:27:
/vagrant/FLEX-mobile/node_modules/react-native/React/Base/RCTBridgeModule.h:58:3: Type specifier missing, defaults to 'int'
/vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.m:24:9: In file included from /vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.m:24:
/vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.h:27:9: In file included from /vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.h:27:
/vagrant/FLEX-mobile/node_modules/react-native/React/Base/RCTBridgeModule.h:60:1: Unknown type name 'RCT_EXTERN_C_END'
/vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.m:24:9: In file included from /vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.m:24:
/vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.h:27:9: In file included from /vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.h:27:
/vagrant/FLEX-mobile/node_modules/react-native/React/Base/RCTBridgeModule.h:65:1: Cannot combine with previous '(error)' declaration specifier
/vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.m:24:9: In file included from /vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.m:24:
/vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.h:27:9: In file included from /vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.h:27:
/vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.m:66:1: Unknown type name 'RCTMethodInfo'
/vagrant/FLEX-mobile/node_modules/react-native/React/Base/RCTBridgeModule.h:155:3: Expanded from macro 'RCT_EXPORT_METHOD'
/vagrant/FLEX-mobile/node_modules/react-native/React/Base/RCTBridgeModule.h:185:3: Expanded from macro 'RCT_REMAP_METHOD'
/vagrant/FLEX-mobile/node_modules/react-native/React/Base/RCTBridgeModule.h:261:12: Expanded from macro '_RCT_EXTERN_REMAP_METHOD'
/vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.m:66:1: Unknown type name 'RCTMethodInfo'
/vagrant/FLEX-mobile/node_modules/react-native/React/Base/RCTBridgeModule.h:155:3: Expanded from macro 'RCT_EXPORT_METHOD'
/vagrant/FLEX-mobile/node_modules/react-native/React/Base/RCTBridgeModule.h:185:3: Expanded from macro 'RCT_REMAP_METHOD'
/vagrant/FLEX-mobile/node_modules/react-native/React/Base/RCTBridgeModule.h:262:12: Expanded from macro '_RCT_EXTERN_REMAP_METHOD'
Parse Issue Group
/vagrant/FLEX-mobile/node_modules/react-native/React/Base/RCTBridgeModule.h:54:1: Expected identifier or '('
/vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.m:24:9: In file included from /vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.m:24:
/vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.h:27:9: In file included from /vagrant/FLEX-mobile/node_modules/react-native-localization/ReactLocalization.h:27:
`

**Comment by stefalda** [comment]
Hi, 
I've just tested with the latest version of RN and everything works fine so I guess there must be some other problem in your project.

Try to open it directly in XCode to get some more informations...
