### ISSUE TITLE
Missing requiresMainQueueSetup

### ISSUE THREAD

**Issue by stami** [stefalda/ReactNativeLocalization#102]
Hi!

I got this printed to my console. 

Pretty self-explanatory if someone is willing to contribute by fixing it. :)

> Module ReactLocalization requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by stefalda** [comment]
Fixed with this [pull request](https://github.com/stefalda/ReactNativeLocalization/pull/109)
