### ISSUE TITLE
Auto change language when change language of device

### ISSUE THREAD

**Issue by Donhv** [stefalda/ReactNativeLocalization#107]
I want my app auto change language when I change language my device. 
Now I must re-start app to change.
Who can help me?

**Comment by stefalda** [comment]
Hi,
 I guess you should subscribe to some system notifications...

But you should dig into platform specific implementations...

**Comment by Donhv** [comment]
https://blog.callstack.io/react-native-handling-language-changes-on-android-the-right-way-c883056a8f5c
solve my issue.
