### ISSUE TITLE
Cannot read property 'language' of undefined

### ISSUE THREAD

**Issue by suntehnik** [stefalda/ReactNativeLocalization#110]
![discounts-mainactivity-02022018154855](https://user-images.githubusercontent.com/1324469/35733995-9ba3b82c-0830-11e8-9fff-360f94984827.png)
Having troubles in running on Android, however iOS works well.
Checked my settings.gradle, build.gradle and MainApplication.java

All looks good, however I cannot start my app.

I see a message 'Cannot read property 'language' of undefined' on console.

**Comment by stefalda** [comment]
Sorry, I've not checked the latest Android version... I don't know if something has changed...

Anybody else has the same problem?

**Comment by suntehnik** [comment]
You can reproduce it in emulator. I used 5.0 Android in emulator.

**Comment by stefalda** [comment]
Hi @suntehnik, just tested with this versions 

```
 "dependencies": {
     "react": "16.2.0",
     "react-native": "0.53.0",
     "react-native-localization": "^0.2.3"
   },
```
and everything compiles and works as expected.

Try to create a new project with `react-native init AwesomeProject`, launch once, close all the windows, and then install the React Native Library (at least this is how I did it...)
