### ISSUE TITLE
1.0.1 installs strangely

### ISSUE THREAD

**Issue by RobinBobin** [stefalda/ReactNativeLocalization#113]
Hi!

When I use

    npm i --save react-native-localization

in my RN project directory, no error message is output, I get

    + react-native-localization@1.0.1
    added 20 packages from 85 contributors in 11.555s

, but when I go to `node_modules/react-native-localization/android` I see only one file there, ` build.gradle`, and my react native project fails to build. Am I doing something wrong?

Thanks.

**Comment by stefalda** [comment]
Sorry, there was a problem with .npmignore, I've fixed it and realeased version 1.0.3

**Comment by RobinBobin** [comment]
Thanks a lot. Great work!
