### ISSUE TITLE
doesn't work on Android

### ISSUE THREAD

**Issue by Aleksandern** [stefalda/ReactNativeLocalization#114]
error on Android (works okay on iOS)

```
import AppWithNavigationState from './AppNavigator';

let strings = new LocalizedStrings({
  en: {
    asd: "asd"
  },
});
```
![2018-03-22_18-20-30](https://user-images.githubusercontent.com/5274465/37767990-9509b14e-2dfe-11e8-87e9-5339f0fa7274.png)

```
"react-native": "0.54.2",
"react-native-localization": "^1.0.3"
```

**Comment by stefalda** [comment]
Hi,
 it seems a problem with decorator support in the Android web engine...

check this [issue](https://github.com/facebook/react-native/issues/15902) and temporary solution:

> I had the same problem a few days back and I think I solved it with an babel preset. I used
> ["react-native-stage-0", "react-native-stage-0/decorator-support"]
> babel-preset-react-native-stage-0

**Comment by Aleksandern** [comment]
Thanks Stefano 
I used this way https://github.com/facebook/immutable-js/issues/1305#issuecomment-341308925

```
import 'core-js/es6/symbol'; 
import 'core-js/fn/symbol/iterator';
```

**Comment by stefalda** [comment]
Hi,
 I've released a new version that doesn't require the polyfill...

**Comment by woshi82** [comment]
I have just try, it's work in android with production release
