### ISSUE TITLE
proper usage of formatString

### ISSUE THREAD

**Issue by FutureGUIs** [stefalda/ReactNativeLocalization#115]
Unless I'm missing something how should I use formatString to return a parameterized string with the parameters replaced as a string?  The old version before 1.x simply returned the formatted string, now it returns an array that it looks like I can manually join back together?

**Comment by emretekince** [comment]
same here

**Comment by stefalda** [comment]
Sorry, there was an error in the code.
I've fixed it and released a new version.

**Comment by stefalda** [comment]
Sorry, I've created a fix because there must be a different behaviour if the formatted text includes a React Component or only strings.

Let me know if it works as expected...

**Comment by FutureGUIs** [comment]
In react-localization the function looks like it'll work now.  Just need the typescript definition updated :)

**Comment by stefalda** [comment]
I've updated the typescript definition.
Thanks
