### ISSUE TITLE
React Android Support

### ISSUE THREAD

**Issue by ling-wong** [stefalda/ReactNativeLocalization#12]
Now that React Android has been released, will you be supporting that as well?

**Comment by stefalda** [comment]
Yes, I've almost completed the android versione and I plan to update it in a few days

**Comment by ling-wong** [comment]
Awesome! Thanks! This is such a great project!


On 23 Sep 2015, at 5:16 PM, Stefano Falda <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, I've almost completed the android versione and I plan to update it in a few days
