### ISSUE TITLE
Compilation Issue (Android)

### ISSUE THREAD

**Issue by rtman** [stefalda/ReactNativeLocalization#120]
All of a sudden this package is failing to compile in dev mode. Not sure what happened, but it was working fine and I didn't change anything with it.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find any version that matches com.facebook.react:react-native:0.11.+.
  Versions that do not match:
      0.20.1
      0.14.0
      0.12.0
      0.54.3
  Searched in the following locations:
      file:/C:/Users/NAME/AppData/Local/Android/sdk/extras/m2repository/com/facebook/react/react-native/maven-metadata.xml
      file:/C:/Users/NAME/AppData/Local/Android/sdk/extras/m2repository/com/facebook/react/react-native/
      file:/C:/Users/NAME/AppData/Local/Android/sdk/extras/google/m2repository/com/facebook/react/react-native/maven-metadata.xml
      file:/C:/Users/NAME/AppData/Local/Android/sdk/extras/google/m2repository/com/facebook/react/react-native/
      file:/C:/Users/NAME/AppData/Local/Android/sdk/extras/android/m2repository/com/facebook/react/react-native/maven-metadata.xml
      file:/C:/Users/NAME/AppData/Local/Android/sdk/extras/android/m2repository/com/facebook/react/react-native/
      https://jitpack.io/com/facebook/react/react-native/maven-metadata.xml
      https://jitpack.io/com/facebook/react/react-native/
      file:/C:/Users/NAME/.m2/repository/com/facebook/react/react-native/maven-metadata.xml
      file:/C:/Users/NAME/.m2/repository/com/facebook/react/react-native/
      https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml
      file:/C:/Projects/APPNAME/node_modules/react-native/android/com/facebook/react/react-native/maven-metadata.xml
      https://maven.google.com/com/facebook/react/react-native/maven-metadata.xml
      https://maven.google.com/com/facebook/react/react-native/
  Required by:
      project :app > project :react-native-localization
```
In `ReactNativeLocalization/android/build.gradle` the following line seems to be what it's referring to:
```
dependencies {
    compile 'com.facebook.react:react-native:0.11.+'
}
```

I tried changing it to:

```
dependencies {
    compile 'com.facebook.react:react-native:0.20.1+'
}
```

It managed to get a little further, but broke with the following error:
```
> Task :app:compileDebugJavaWithJavac FAILED
C:\Projects\APPNAME\android\app\src\main\java\com\appname\appname\MainApplication.java:13: error: cannot find symbol
import com.babisoft.ReactNativeLocalization.ReactNativeLocalizationPackage;
                                           ^
  symbol:   class ReactNativeLocalizationPackage
  location: package com.babisoft.ReactNativeLocalization
C:\Projects\APPNAME\android\app\src\main\java\com\appname\appname\MainApplication.java:61: error: cannot find symbol
          new ReactNativeLocalizationPackage(),
              ^
  symbol: class ReactNativeLocalizationPackage
2 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

Not sure what to do here, please have a look.

**Comment by halcyonnx** [comment]
Found temporary workaround by changing dependency in `node_module/react-native-localization/build.gradle` from `0.11.+` to whatever react-native version you are using. For instance `0.55.3`.

**Comment by nasmuris** [comment]
This problem seems to be outside this lib, I'm having the same issue with several other RN libraries

**Comment by rtman** [comment]
I tried `0.54.3` as my `package.json` states:

```
    "react-native": "^0.54.3", 
```
```
dependencies {
    compile 'com.facebook.react:react-native:0.54.3+'
}
```

I get the same error I posted above. @nasmuris any idea whats going on?

**Comment by nasmuris** [comment]
I have no idea... but for me setting `compile 'com.facebook.react:react-native:0.54.3'` in libs causing issues worked fine (the other one was react-native-locale), still it's just a temporary "fix"

**Comment by rtman** [comment]
just to be clear we are talking about 'node-modules\react-native-localization\android\build.gradle` right?

If so, seems to not work for me.... arghh

**Comment by rtman** [comment]
@nasmuris what version of react-native-localization are you using?

**Comment by nasmuris** [comment]
sorry, I'm using RN 0.55.3 so im setting `dependencies {
    compile 'com.facebook.react:react-native:0.55.3'
}` in the `node-modules\react-native-localization\android\build.gradle` 
as I stated before, I had the same issue with other lib (react-native-locale) so I've made the same change also in `node-modules\react-native-locale\android\build.gradle`
`"react-native-localization": "^0.1.32",`

**Comment by rtman** [comment]
@nasmuris thanks

So i moved to `react-native-localization": "^0.1.32` and apparently it works now even with 
```
dependencies {
    compile 'com.facebook.react:react-native:0.11.+'
}
```

No idea what happened or what fixed it... :) :(

**Comment by ShaMan123** [comment]
Had the same problem. Fixed with this change:
`dependencies {
    compile 'com.facebook.react:react-native:+'
}`

**Comment by stefalda** [comment]
I've merged the solution to current version... thanks

**Comment by taylorkline** [comment]
@stefalda This is suddenly happening again for me; anyone else?

**Comment by taylorkline** [comment]
Fixed by completely removing the `android/` folder and then just restoring the git tracked files. I'm not sure why that worked when I had already done a gradle clean, but it thankfully did.
