### ISSUE TITLE
Gradle error build: compileSdk

### ISSUE THREAD

**Issue by rkostrab** [stefalda/ReactNativeLocalization#125]
In version `1.0.11` I am getting gradle error:
```
Gradle sync failed: Cannot get property 'compileSdkVersion' on extra properties extension as it does not exist
Consult IDE log for more details (Help | Show Log) (33s 496ms)
```

**Comment by socheat1994** [comment]
Did you solve your problem? please update your solution. 
I am also facing with this problem.

**Comment by socheat1994** [comment]
Hey @rkostrab  let try with my solution, I just solved it. 
go to /node_modules/react-native-localization/android/build.gradle file
open and replace with this code. or you can check each of version that relates to your project.

`buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
    }
}

apply plugin: 'com.android.library'

def _ext = rootProject.ext;

def _reactNativeVersion = _ext.has('reactNative') ? _ext.reactNative : '+';
def _compileSdkVersion = _ext.has('compileSdkVersion') ? _ext.compileSdkVersion : 26;
def _buildToolsVersion = _ext.has('buildToolsVersion') ? _ext.buildToolsVersion : '26.0.1';
def _minSdkVersion = _ext.has('minSdkVersion') ? _ext.minSdkVersion : 16;
def _targetSdkVersion = _ext.has('targetSdkVersion') ? _ext.targetSdkVersion : 26;

android {
    compileSdkVersion _compileSdkVersion
    buildToolsVersion _buildToolsVersion

    defaultConfig {
        minSdkVersion _minSdkVersion
        targetSdkVersion _targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}

dependencies {
    //noinspection GradleDynamicVersion
    provided "com.facebook.react:react-native:${_reactNativeVersion}"
}
`

**Comment by stefalda** [comment]
You’re right. I’ll add it to the ReadMe.

**Comment by rkostrab** [comment]
FYI: 1.0.11 is compatible >= RN 0.56.0

**Comment by matthewmayer** [comment]
Just ran into this problem, it might be preferable to make removing support for older versions of RN  a semver-major change, so version number should be 2.0.0 to avoid breaking old installations?

**Comment by stefalda** [comment]
@matthewmayer you're right...
I've published two new versions to npm restoring the old functionality for version 1.x and adding the new behaviour just for version >2.x
