### ISSUE TITLE
missing fallback option?

### ISSUE THREAD

**Issue by stefan-korfitz** [stefalda/ReactNativeLocalization#126]
Correct me if im wrong, but I can't seem to figure out how I should set a fallback language using this dependency?... Is it missing? or just not described in the docs? - Either way, I would like to suggest an enhancement regarding this ;-)

**Comment by stefalda** [comment]
Hi, the fallback language is the first defined language...

**Comment by stefan-korfitz** [comment]
Hello :-)

Thank you for your reply!... 

Have you tested this? Because when I switch to language on my tablet, that I haven't defined in my json object in my app, then it makes the app crash!

And second... If this is your intention in your design, then perhaps you could make it a bit more cleare in your documentation ?! Because, nowhere did it say, that the the first defined language is surposed to act as a fallback language...

Best regards
- Stefan

**Comment by stefalda** [comment]
Hi,
 I'll make it crearer in the documentation.

About the crash... it depends on how the Language class is implemented and the platforms beahave differently in object allocations so it's difficult to tell where's the problem...

Stefano
