### ISSUE TITLE
update readme at npm website

### ISSUE THREAD

**Issue by nielsswinkels** [stefalda/ReactNativeLocalization#127]
On the [npmjs site ](https://www.npmjs.com/package/react-native-localization)the line "To simplify Android versions' configuration, versions 1.0.11 and up are compatible only with ReactNative >= 0.56.0" is not part of the readme text. Can this be updated there?

**Comment by stefalda** [comment]
I've published two new versions to npm restoring the old functionality for version 1.x and adding the new behaviour just for version >2.x
