### ISSUE TITLE
show FIND instead of string in my local string 

### ISSUE THREAD

**Issue by Shabnam-Veranloo** [stefalda/ReactNativeLocalization#132]
i have a local string that have two language , 
sometimes don't show my string and show FIND 
for example i have hello in my string in my local when i write this code(strings.hello) show FIND instead of hello,why?

**Comment by stefalda** [comment]
Have you got some code to share?
thanks

**Comment by Shabnam-Veranloo** [comment]
@stefalda my problem was for react-navagation component...
i downgrade version that and show string 
thanks for reply
