### ISSUE TITLE
Compilation issue Android

### ISSUE THREAD

**Issue by fega** [stefalda/ReactNativeLocalization#133]
Hello, I'm trying to install the package but when I run ``npm run android`

I get the following error:

```
> Configure project :react-native-localization
WARNING: The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..
Project evaluation failed including an error in afterEvaluate {}.
java.lang.IllegalStateException: compileSdkVersion is not specified.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:456)
```

**Comment by fega** [comment]
iI got working after revert those changes:

https://github.com/stefalda/ReactNativeLocalization/pull/123/files#diff-7ae5a9093507568eabbf35c3b0665732R6

**Comment by stefalda** [comment]
Hi, 
what version of RN are you using because 'versions 2.0 and up are compatible only with ReactNative >= 0.56.0'...?

**Comment by fega** [comment]
Yes, that's the issue, thanks
