### ISSUE TITLE
Results from getInterfaceLanguage and NativeModules.I18nManager not equal

### ISSUE THREAD

**Issue by MaciekLeks** [stefalda/ReactNativeLocalization#134]
I use PL_SP language (Silesian on polish base) on my device but the lib doesn't recognize it and assumes I use en-US. I've check it out with the code:

```javascript
const l1 = NativeModules.I18nManager.localeIdentifier; // res: PL_SP (corrent)
const l2 = strings.getInterfaceLanguage(); // res: en-US (incorrect)
```
What could be wrong?

**Comment by ACOSW** [comment]
@MaciekLeks are you using rn0.57+ version ?
I have same problem after i've upgraded to 0.57

**Comment by MaciekLeks** [comment]
@ACOSW, nope, I use rn0.56.0.

**Comment by pavel-zlotarenchuk** [comment]
I have exactly the same problem

**Comment by goodhyun** [comment]
@stefalda it looks like the language detection module is somewhat broken recently and this is a deal breaker.

**Comment by stefalda** [comment]
I hope to be able to make some test this weekend...
