### ISSUE TITLE
Something went wrong initializing the native ReactNativeLocalization module. Please check your configuration.

### ISSUE THREAD

**Issue by JayeshPoriya** [stefalda/ReactNativeLocalization#135]
Hi everyone, 
Can anyone help me? 
I want to use this lib & I am developing in mac system.  
Everything is fine until I import localization file. 
When I 
**import LocalizedStrings from 'react-native-localization';**
I got an error 
**Something went wrong initializing the native ReactNativeLocalization module.
Please check your configuration.
Did you run 'react-native link'?**
![file](https://user-images.githubusercontent.com/16848686/46942093-36e76a00-d08a-11e8-8a81-77a907fb4c24.jpg)
Please check this screenshot and help me. 

npm --version
6.4.1
expo --version
2.2.0
react-native --version
react-native-cli: 2.0.1
react-native: 0.55.4
expo cli --version
2.2.0

Thank you.

**Comment by joelcogen** [comment]
I have the same issue
* expo: 30.0.1
* react: 16.3.1
* react-native-cli: 2.0.1
* react-native: 0.55.4

**Comment by stefalda** [comment]
Hi,
 please check the read me...

**"Beware Expo created apps need to be ejected before integrating native plugins like this one. So if you've used the Create React Native app shortcut you should eject the app as detailed here here."**

**Comment by fega** [comment]
Having same issue with the same react-native version, but I'm not using expo

**Comment by JayeshPoriya** [comment]
OK, 
Thanks for reply @stefalda

**Comment by IAmAbhishekTomar** [comment]
So this plugin not supporting Expo? :(

**Comment by stefalda** [comment]
I'd say it's the other way around ;-)

**Comment by iconicsammy** [comment]
I am getting the error in a typescript driven app. That same version did work in my previous js driven application, just in case it matters.
