### ISSUE TITLE
Incorrect package name

### ISSUE THREAD

**Issue by rockerhieu** [stefalda/ReactNativeLocalization#14]
Both `ReactNativeLocalization` and `ReactNativeLocalizationPackage` are declared in the incorrect package. It should be `com.babisoft` instead of `com.babisoft.ReactNativeLocalization`.

**Comment by stefalda** [comment]
You're right... the ReactNativeLocalization folder is missing... I'll check with Android Studio.
Thank you

**Comment by stefalda** [comment]
Fixed.
