### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by 2xSamurai** [stefalda/ReactNativeLocalization#144]
Hi. First of all great plugin by the way. I am new to react native and was wondering, is there any chance that this plugin can switch the app to RTL mode. Like when setting Language to Arabic, the app should switch to RTL right. Can I achieve it with this plugin or do I need to do something else? Can somebody shine some light on this for me? Thanks in Advance.

**Comment by stefalda** [comment]
Hi @2xSamurai, 
I fear you should use another plugin to achieve this, change the RTL is currently not supported.

**Comment by 2xSamurai** [comment]
@stefalda Thank you. I ended altering the stylesheet for RTL based on a variable.
