### ISSUE TITLE
undefined is not an object (evaluating 'localization.language') 

### ISSUE THREAD

**Issue by PCharpentier** [stefalda/ReactNativeLocalization#15]
Hi,

I use your package in my app.
I work on windows with a device and it works. I try to work on Mac with Genymotion and I have a problem  : undefined is not an object (evaluating 'localization.language')
The problem is on LocalizedStrings.js line 17.

I think it doesn't find the language ?

**Comment by franfran** [comment]
Did you add the link library in xcode?  I had the same issue and I found I forgot to add the link.  See the installation in readme.

**Comment by PCharpentier** [comment]
I reload today my app and it works. I don't know why.
Thanks for your help.
