### ISSUE TITLE
Having issue in iOS during build and archive in Xcode  getting error no such file or directory with libReactNativeLocalization.a

### ISSUE THREAD

**Issue by imsantoshyadav** [stefalda/ReactNativeLocalization#151]
Hi,

I am using 2.0.3 version of your package I am getting error in iOS compilation where when I try to build or archive the project it throws error `no such file or directory: '/Users/...../DerivedData/myproject/Build/Products/Debug-iphonesimulator/libReactNativeLocalization.a'` .

- it is working completely fine for android version but shows error for iOS.

- I have installed package with `npm install react-native-localization --save` and also linked with `react-native link react-native-localization`
- Also linked library manually as suggested by documentation for iOS.
- in xcode my Deployment target is set to 9.0

**Comment by thuan-nguyen-logivan** [comment]
open your xcode project
try to remove and add libReactNativeLocalization.a again in `Build Phases` -> `Link Bynary with Libraries`
clean project and build again.

**Comment by imsantoshyadav** [comment]
@thuan-nguyen-logivan thanks for your reply I have already tried it but didn't worked for me

**Comment by imsantoshyadav** [comment]
To get rid of this issue I have commented  `pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'` in podfile and run `pod install` after that i have linked library manually and it workd for me

**Comment by imsantoshyadav** [comment]
Because this solution worked for me I am closing this issue

**Comment by thuan-nguyen-logivan** [comment]
oh, i forget it 👍
