### ISSUE TITLE
Make LocalizedStrings.js independent of 'react-native'

### ISSUE THREAD

**Issue by BenKewell** [stefalda/ReactNativeLocalization#16]
I'm finding a way to do localization in the same way across react-native and browser based react for better consistency.
It turns out that by simply replacing the lines in LocalizedStrings.js
```
var localization = require('react-native').NativeModules.ReactLocalization;
var interfaceLanguage = localization.language;
```
with
```
let interfaceLanguage = (navigator.language || navigator.userLanguage);
```
the class will work just fine in browser.

So as a suggestion, I think the class itself could be made as a platform independent library.
For 'react-native' and browser, provide a wrapper module to pass in the correct device locale automatically.
Then we can have the same way to do localization across all react apps.

**Comment by stefalda** [comment]
Hi,
 sorry for the delay...

Could work something like this?

```javascript
let interfaceLanguage = null;

if (navigator){
  	interfaceLanguage = (navigator.language || navigator.userLanguage);
} else {
	let localization = require('react-native').NativeModules.ReactLocalization;
	interfaceLanguage = localization.language;
}
```

Let me know

Stefano

**Comment by BenKewell** [comment]
This doesn't work on Browserify, my Gulp setup gives some error like this:

Error: Cannot find module 'react-native'

Currently I can use the class in browser by copying the whole "LocalizedStrings.js" file and edit it.
Since 'react-native' is completely not used in browser, I don't think installing 'react-native' as dependency is a good choice.

**Comment by stefalda** [comment]
It seems you could ad react-native to the excluded or ignored list in the browserify config file

http://stackoverflow.com/questions/23249826/browserify-nested-conditional-requires

**Comment by BenKewell** [comment]
Sorry can't get it working even with the ignore setting, some other strange error relating to react-native comes up.

Since the localization module itself is quite simple,
the simplest way to use it in browser will be to fork it and change the line of interfaceLanguage declaration.
May be add this as a note on the documentation and then just close this issue?

**Comment by stefalda** [comment]
I've made some tests but in the end I decided to create a simplier library with no dependencies to share the same code used in ReactNative project with a React project.
You can find it here: [react-localization](https://github.com/stefalda/react-localization).

**Comment by BenKewell** [comment]
The new module works perfectly. Thanks for your effort.
