### ISSUE TITLE
Fix wrong locale returned on iOS

### ISSUE THREAD

**Issue by winkelsdorf** [stefalda/ReactNativeLocalization#161]
## Steps to reproduce
- Set system language to english
- Set region to germany (decimal separator becomes `,`)
- Use `console.log(Translations.getInterfaceLanguage());`

## Expected
Reported interface language should be `en-DE`.

## Actual
`en-US` is returned.

## Fix
Use `localeIdentifier` in objc. See PR #160 for corrected implementation and comments.

**Comment by winkelsdorf** [comment]
Closed as PR #160 was merged

**Comment by iKonrad** [comment]
Has this actually been fixed? Instead of `pl-PL` I'm getting `en-PL` with both Polish language and region.

**Comment by winkelsdorf** [comment]
@iKonrad yes my change has been merged. What device/which iOS are you running? Going to try pl/PL with your settings then. But it should work as it returns just what iOS gives.

**Comment by iKonrad** [comment]
I'm using iPhone X 12.2 simulator - would that make any difference? Will try with a real device shortly

**Comment by winkelsdorf** [comment]
No, that should be fine: only iOS older than iirc 10.0 need and use the implemented fallbacks. So with iOS 12 it’s irritating.

You updated your npm packages including this, recompiled your App in Xcode (required!) and did a `startfresh` of the packager?
