### ISSUE TITLE
strings.getLocaleObject is not a function

### ISSUE THREAD

**Issue by cesarve77** [stefalda/ReactNativeLocalization#167]
I just did a search in your code and there is not reference togetLocaleObject

But it is in the docs

**Comment by cesarve77** [comment]
I solved using 

```
strings.setContent(Object.assign({},strings._props,
{
  en:{
    how:"How do you want your egg todajsie?",
    boiledEgg:"Boiled eggsie",
    softBoiledEgg:"Soft-boiled egg",
    choice:"How to choose the egg"
  }
}));
```

**Comment by stefalda** [comment]
I didn't find any strings.getLocaleObject in the docs... where have you found it?

**Comment by cesarve77** [comment]
You can also only overwrite a specific language using

strings.setContent(Object.assign({},strings.getLocaleObject(),
{
  en:{
    how:"How do you want your egg todajsie?",
    boiledEgg:"Boiled eggsie",
    softBoiledEgg:"Soft-boiled egg",
    choice:"How to choose the egg"
  }
}));

**Comment by stefalda** [comment]
Thanks, I've fixed the documentation!

**Comment by cesarve77** [comment]
Great, thanks!
