### ISSUE TITLE
Language is stuck to en / en-US

### ISSUE THREAD

**Issue by VincentCATILLON** [stefalda/ReactNativeLocalization#168]
## Purpose

The `getLanguage()` and `getInterfaceLanguage()` returned values are stuck to `en` and `en-US` respectively, no matter the iPhone language I chose.

Regression source: https://github.com/stefalda/ReactNativeLocalization/commit/2a3e91c48095dd3d5fe58d1059179da438a882e1

## Environment

- `react-native`: 0.59.8
- `react-native-localization`: 2.1.2
- `iOS`: 12.1

## Quick fix

Rollbacking to `2.1.0` (i didn't tested the `2.1.1`) fixed the issue.

## Side effect

Btw, `getInterfaceLanguage()` returns `de-US` when I chose `Deutsch` general language, which seems to be a unicorn country 🦄

**Comment by eminsr** [comment]
Updating the library to 2.1.3 will fix this issue. #166

**Comment by VincentCATILLON** [comment]
@eminsr i'll try tomorrow. thanks
