### ISSUE TITLE
Does this support Google app localization? Works exactly same to res/values/strings.xml in native android project?

### ISSUE THREAD

**Issue by mevanso01** [stefalda/ReactNativeLocalization#169]
I'm now struggling to implement Google android app localization feature in react native project. For now, I don't know how to pass the native android strings resource to react native context. Surfing the internet, I found several modules such as react-native-localization, react-native-i18n, but I'm not sure which one will solve my issue.
So I'd like to know if this one works same as native android project strings resource file.
Can anyone help me on this?

**Comment by stefalda** [comment]
Hi, this project aims to solve the localization problem completely from JS so it doesn't use the native android solution...

**Comment by mevanso01** [comment]
Thanks on your kind support.
