### ISSUE TITLE
Autolinking is not supported

### ISSUE THREAD

**Issue by Bartson** [stefalda/ReactNativeLocalization#170]
Right now it isn't possible to install react-native-localization in 0.6 react native version properly. I've read about disabling autolinking in not supported library but it doesn't work. Any solutions?

**SOLUTION BY NOW:**
It's necessary to disable autolinker on the react-native-localization library. Add:

 ```
 dependencies: {
    'react-native-localization': {
      platforms: {
        android: null, // disable Android platform, other platforms will still autolink if provided
      },
    },
  },
```
to your react-native.config.js file. Next step is just to link library as the doc says. Anyway, hope this library will be supported with autolinker someday.

**Comment by Bartson** [comment]
Ok, it's solution just for android. When I added line with: `ios: null` it's not working.

**Comment by Bartson** [comment]
To make it work on iOS you need to do `cd ios` and `pod install`.

**Comment by stefalda** [comment]
Hi, I've just reviewed the library and updated the install information to make it compliant to react-native 0.60.

Check this [article](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) about the new linking behaviour in react-native since version 0.60.
