### ISSUE TITLE
ITMS-90683: Missing Purpose String in Info.plist

### ISSUE THREAD

**Issue by unutoiul** [stefalda/ReactNativeLocalization#171]
ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

Message from Apple after submitting my APP.

**Comment by stefalda** [comment]
Hi @unutoiul , the error has **nothing** to do with this library.
It just says that you are using the phone GPS (NSLocationAlwaysUsageDescription) without providing a localized reason of why you're doing so...
