### ISSUE TITLE
null is not an object (evaluating 'localization.language') -> IOS ONLY issue

### ISSUE THREAD

**Issue by enigmablue** [stefalda/ReactNativeLocalization#176]
Am on 

"react-native": "0.60.1",
"react-native-localization": "^2.1.6",

Build is fine but crashes when i try to run the app. I've followed the instructions on yarn install, pod install, and even tried manual linked via the project navigator -> libraries reactnativelocalization.xcodeproj. 

Eventually the error ends up with "Something went wrong initializing the native ReactNativeLocalization module".

Any clues? 

> TypeError null is not an object (evaluating 'localization.language') 
>     http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:197268:24 getInterfaceLanguage
>     http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:197496:67 LocalizedStrings
>     http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:197277:123 LocalizedStrings
>     http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:197085:53 
>     http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:250:14 loadModuleImplementation
>

**Comment by sagarbhatt4** [comment]
do you get any solution regarding this?

**Comment by NitishSystango** [comment]
I am also getting the same issue. Any solution for this?

**Comment by enigmablue** [comment]
I'm just using https://github.com/zoontek/react-native-localize now

**Comment by goodhyun** [comment]
Complete rebuilding and restarting your package might help the issue.

**Comment by engin-y** [comment]
anyone resolved this without migrating to another library? rebuild is no help.

**Comment by mletada** [comment]
how about android? Anybody face this issue?
