### ISSUE TITLE
Get the list of existing languages

### ISSUE THREAD

**Issue by programmaker** [stefalda/ReactNativeLocalization#184]
Hi.
I do have the dictionary with several languages and from time to time I'm adding more languages/translations. How can I get list of existing translations dynamically?
(e.g. in react-native-localize we can do RNLocalize.getLocales())
Thanks.

**Comment by stefalda** [comment]
Hi,
 you can call this method:

`strings.getAvailableLanguages()
`

it returns an array of the passed languages.
