### ISSUE TITLE
Language matching doesn't account for scripts

### ISSUE THREAD

**Issue by seanrogs** [stefalda/ReactNativeLocalization#19]
The language matching function just cuts straight to the language tag and ignores any other relevant identifying tags. For example, `zh-Hans-CN` goes straight to `zh` instead of to `zh-Hans`.

Pull request here: https://github.com/stefalda/ReactNativeLocalization/pull/18

**Comment by stefalda** [comment]
Thanks for the PR.
I've committed it...
Stefano
