### ISSUE TITLE
Class ReactLocalization was not exported

### ISSUE THREAD

**Issue by dwilt** [stefalda/ReactNativeLocalization#2]
Ran through your installation steps, all worked fine - added the 2 files to the project:
![screenshot 2015-04-30 07 46 29](https://cloud.githubusercontent.com/assets/1065539/7415343/117d7c44-ef0d-11e4-8476-aba398dcdf26.png)

**Note, I am getting this warning about `RCT_EXPORT`:**
![screenshot 2015-04-30 07 47 35](https://cloud.githubusercontent.com/assets/1065539/7415367/2e1116f4-ef0d-11e4-88c1-f2ee2b81195f.png)

In my index.ios.js, I added: 
`var LocalizedStrings = require('./node_modules/react-native-localization/LocalizedStrings');`

I run project through Xcode and get this:
![screenshot 2015-04-30 07 48 48](https://cloud.githubusercontent.com/assets/1065539/7415388/59c2fc0e-ef0d-11e4-9a9c-57b9a8efce56.png)

**Comment by stefalda** [comment]
Release 0.4 of ReactNative changed the way methods are exported, I'm going to make the required changes...

**Comment by stefalda** [comment]
I've fixed the code.
If you experience a blank screen remove the node_modules dir (```rm -rf node_modules```),
add react-native-localization as dependency to your package.json file (```"react-native-localization": "^0.1.2"```) and type ```npm install```.

**Comment by dwilt** [comment]
Yep, that fixed it. Thanks!

Sorry if you didn't mean to be resolving bugs for other people :)

**Comment by stefalda** [comment]
I'm happy to help :-)
