### ISSUE TITLE
react-native-web support

### ISSUE THREAD

**Issue by sdevansh96** [stefalda/ReactNativeLocalization#204]
How to run this package in web if we are using react-native-web?

**Comment by stefalda** [comment]
Why don't you use the react-localization package?

[https://github.com/stefalda/react-localizatio](https://github.com/stefalda/react-localization)

**Comment by sdevansh96** [comment]
Will use react-localization, thanks for the quick response.

**Comment by quicksilverr** [comment]
Just to add a point here - 
In your resolve alias of your web pack config - 
```
config.resolve.alias = {
      'react-native': 'react-native-web',
      'react-native-linear-gradient': 'react-native-web-linear-gradient',
      'react-native-localization': 'react-localization'
    };
```

**Comment by Parmar-Bansi** [comment]
> Just to add a point here - In your resolve alias of your web pack config -
> 
> ```
> config.resolve.alias = {
>       'react-native': 'react-native-web',
>       'react-native-linear-gradient': 'react-native-web-linear-gradient',
>       'react-native-localization': 'react-localization'
>     };
> ```

thank you..
