### ISSUE TITLE
Issue regarding React native localization

### ISSUE THREAD

**Issue by DeToxer** [stefalda/ReactNativeLocalization#21]
Hey stelfalda!

I ran into an issue when using your repo. In my android emulator (im using Windows OS), when running the code, i get an error;
"undefined is not an object (evaluating 'localization.language').
Is this an exception that is familiar to you? The problem seems to be located in LocalizedStrings.js
I did the installation exactly as described.

![image](https://cloud.githubusercontent.com/assets/13535388/13107554/8d4b2cd4-d56e-11e5-8ede-a6b882c340c9.png)

![image](https://cloud.githubusercontent.com/assets/13535388/13107509/545da352-d56e-11e5-84bb-2cacbe9a68a1.png)

Thanks in advance,

Martin

**Comment by stefalda** [comment]
What version of RN are you using?

**Comment by DeToxer** [comment]
Currently running RN 0.20.0

**Comment by stefalda** [comment]
Hi,
 just tested with RN 0.20.0, it seems there's some problem with one of the configuration files so ReactLocalization is not loaded properly...

Recheck the Android install instructions...

**Comment by lapcchan** [comment]
we followed the manual android installation instruction on https://github.com/stefalda/ReactNativeLocalization

but still with the same error on LocalizedStrings.js
"undefined is not an object (evaluating 'localization.language')

we are using RN 0.29

**Comment by Arkanine** [comment]
Hi, 
I have the same issue. My react-native version is 0.30
I tried 'rnpm install' and manual installations. In both cases result is the same.
Please help me find out the issue.
Regards, Roman

**Comment by stefalda** [comment]
Unfortunately I'm away from my pc but has soon as I get back home I'll try with a more recent version of RN. It's been a while since I've used it. I'll post my results here.

**Comment by DavyDeDurpel** [comment]
I'm facing the same  issue with RN 0.26.3 (and manual installation)

**Comment by DavyDeDurpel** [comment]
I made the issue disappear by importing LocalizedStrings in the same file where I create the application.  
I'm using react-native-navigation so my application gets started in a non-standard way. I'm not sure if this workaround will also work for applications that start in the standard RN way.

**Comment by Chris-Petty** [comment]
I'm also running into this issue on RN 0.30.0. Freshly installed via rnpm today into an existing project, tested in android emulator.

<img width="548" alt="screen shot 2016-08-15 at 1 25 48 pm" src="https://cloud.githubusercontent.com/assets/7684221/17653691/31c7d1c0-62ed-11e6-9c11-2a395ebc0743.png">

**Comment by stefalda** [comment]
Hi, I've made some tests, and the problem is that the way modules are imported in Android has changed.

I've updated the instructions and as stated there you should manually execute step 4 of "Manual installation Android".

Let me know if it fixes the problem, for me it's working.

**Comment by DavyDeDurpel** [comment]
That might fix the issue for RN 0.29+ but I see the issue also on RN 0.25.  It only happens when my application is restarted after a crash so it should only happen during the development phase :-)

**Comment by stefalda** [comment]
Maybe the packager has some problem then? Is there a way to reproduce?
Because forcing an error with red screen and then restoring the correct code worked in my tests...

**Comment by DavyDeDurpel** [comment]
For me it only happens after the app itself crashes.  I think the best test would be to throw an error inside the Android Java code.

**Comment by stefalda** [comment]
I don't think it would work, the problem seems to be that the localization object in "undefined" because the require failed, so JS can't see it.

**Comment by DavyDeDurpel** [comment]
My last comment was about how to simulate an application crash.  You have to in one way or another let the application crash and have it restarted by Android.  After the restart we get the above error.
And from that moment the error persists even when doing a 'shake' or 'RR'.

Do you know a good way to have some kind of stack trace in case a require fails?  Then I might provide you with more valuable data.

**Comment by stefalda** [comment]
Ah, ok, now I've understood...
I think you can watch the stacktrace from adb/Android Studio... but I'm not an explert of this kind of hybrid development... I've only developed directly in java for Android...
Have you got an example of how to crash the app from Android?

**Comment by DavyDeDurpel** [comment]
I think I found an easy way to simulate the issue.  I always seem to have it when I rotate my android simulator.  Can you confirm this?

**Comment by stefalda** [comment]
I've tried with the Geny Motion emulator and it works even rotating the "device"...

**Comment by Chris-Petty** [comment]
I'm not having this problem anymore. Had to do step 4 manual android installation as you stated above. Cheers. This is still on RN 0.30. No problem with rotating screen.

**Comment by DavyDeDurpel** [comment]
I digged some deeper in the log files and it seems that this is not the only module that is having problems.  It's just the first one for which I get an exception.  It seems that for one reason or another some of the dependencies just 'disappear' from the javascript context.  Probably a bug in React.
Anyway I guess this issue can be closed.

**Comment by abeikverdi** [comment]
rnpm link caused the issue for me. When I manually followed the steps it worked.

**Comment by arhmnsh** [comment]
@stefalda Hi Stefano! I tried manually installing as you mentioned in Step 4, but then I get this error when I run-android:

<img width="944" alt="screen shot 2016-08-25 at 9 26 00 am" src="https://cloud.githubusercontent.com/assets/1363724/17959014/42f22368-6aa6-11e6-9d6b-996479480060.png">

**Comment by stefalda** [comment]
try using rnpm and then the step 4...

**Comment by arhmnsh** [comment]
Tried rnpm and then the step 4. The error in the screenshots is what I get
after doing it. Also tried completely doing it manually, still same.

On Aug 27, 2016 5:32 PM, "Stefano Falda" <notifications@github.com> wrote:

try using rnpm and then the step 4...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/stefalda/ReactNativeLocalization/issues/21#issuecomment-242920443>,
or mute the thread

**Comment by stefalda** [comment]
Have you tried opening the gradle project in Android Studio and trying to figure out the error in java...

**Comment by Chris-Petty** [comment]
@stefalda completely off topic (if only git still had a PM feature), do you know of any good programs for editing translations in the format used by this library? Sending out the code file with the translations isn't a great option if I need others to translate.

Converting the object code to JSON, then to CSVs for excel seems to mess up the structure.

**Comment by stefalda** [comment]
Sorry, currently I'm not aware of any solution able to do such management.

**Comment by arhmnsh** [comment]
@stefalda I tried opening it in Android Studio. I get an error on start saying:
"Compilation is not supported for ReactNativeLocalization. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project".

Versions:
"react-native": "0.30.0",
"react-native-localization": "^0.1.17",
Android Studio: 2.1.3

![image](https://cloud.githubusercontent.com/assets/1363724/18080309/a142c60c-6e9d-11e6-9843-8d6560829598.png)
