### ISSUE TITLE
Issue with 2.3.0 (missing commit)

### ISSUE THREAD

**Issue by neilco** [stefalda/ReactNativeLocalization#213]
This is just an FYI: 

There's an issue with v2.3.0 in that it's missing a commit from #212. This is because you bumped the version before merging the pull request. As a result, yarn is still not treating `react-native-windows` as an optional dependency and generates an unmet peer dependency warning.  

When you don't use GitHub releases or git tags to specify the latest release, the package registries resolve the latest version to the commit where the version number changed. In this case, you merged the pull request after bumping the version to 2.3.0 and so 2.3.0 doesn't contain everything from #212.

**Comment by stefalda** [comment]
Thanks @neilco I should have fixed it
