### ISSUE TITLE
[question] taking screenshots with snapshot 

### ISSUE THREAD

**Issue by propan** [stefalda/ReactNativeLocalization#22]
Hi,

thanks for publishing the lib.

I was trying to take screenshots using snapshot but the app keeps using the default locale.
And if I manually change the device language, everything works just fine.

Do you have any hints on how to make it work with snapshot?

Thanks,
Pavel

**Comment by stefalda** [comment]
Hi Pavel,
 I've never used snapshot but I've installed and made some tests (great tool BTW!).

Essentially it changes the language settings of the emulator and restart the app so there shouldn't be any problem as long as the language is defined in your strings object.

Here's my results...

![iphone4s-01loginscreen](https://cloud.githubusercontent.com/assets/4984558/13159622/1612dc40-d693-11e5-9b42-7b3b2d30671d.png)

![iphone4s-01loginscreen](https://cloud.githubusercontent.com/assets/4984558/13159624/1de63ae8-d693-11e5-89e2-dc14b49e061b.png)

Sincerely I don't know why it's not working for you.

Stefano

**Comment by propan** [comment]
Hi Stefano,

If I got it right it actually cannot change the language settings of the simulator and instead it uses '-AppleLanguages' and '-AppleLocale' launch arguments to do the trick. I guess there's something wrong with my setup.

Could you please share your test project with fastlane config?

Thanks,
Pavel

**Comment by propan** [comment]
I found the problem. It was my setup as I had thought.

Thank you anyway :)
