### ISSUE TITLE
Does it support tvOS

### ISSUE THREAD

**Issue by venky145** [stefalda/ReactNativeLocalization#224]
[!] The platform of the target `AppName-tvOS` (tvOS 13.0) is not compatible with `ReactNativeLocalization (2.3.1)`, which does not support `tvOS`.

**Comment by stefalda** [comment]
Hi, I beleve there are no limitation to use it with tvos...

If you want you can create a PR and I'll merge it. Thanks

**Comment by venky145** [comment]
it is not working for tvOS so need to remove the library and continue.
any solution?
