### ISSUE TITLE
Return string item from default language if item in desired translation is missing

### ISSUE THREAD

**Issue by rkostrab** [stefalda/ReactNativeLocalization#23]
Let's have this code:
```
import LocalizedStrings from 'react-native-localization';
let strings = new LocalizedStrings({
  en:{
    how:"How do you want your egg today?",
    boiledEgg:"Boiled egg",
    softBoiledEgg:"Soft-boiled egg",
    choice:"How to choose the egg"
  },
  it: {
    how:"Come vuoi il tuo uovo oggi?",
    boiledEgg:"Uovo sodo",
    softBoiledEgg:"Uovo alla coque",
   // notice missing 'choice'
  }
});
```

If I use IT language and pick `strings.choice`, then now I get `undefined` object. It should return `choice` string from `en` (which is first language - thus default). This is also default behavior in Android native projects. 

**Please fix this.**

**Comment by stefalda** [comment]
You're right, it would be a good behavior... I've committed the code
