### ISSUE TITLE
Set General Language!

### ISSUE THREAD

**Issue by rsflow** [stefalda/ReactNativeLocalization#24]
Hi,

Is there a way to set all the `LocalizedStrings` created to a specific language without going to each of them and doing this `strings.setLanguage('it')`?

Thank You!

**Comment by AwesomeJerry** [comment]
+1 or is there any way to create only one strings instance and add key/value pairs to it.

**Comment by stefalda** [comment]
Hi,
 usually I create a singleton with all the strings inside so I can change language and reuse strings from multiple points...

Stefano

**Comment by AwesomeJerry** [comment]
I managed to solve it by creating an object that all other strings instances would register itself to that object when initialized. When changing language, just iterate through all instances and call setLanguage.
It's stupid, but it works!

**Comment by kelvinaliyanto** [comment]
hi @stefalda , do you mind sharing your code on how you achieve this?
