### ISSUE TITLE
Get a string in a specified language

### ISSUE THREAD

**Issue by fender** [stefalda/ReactNativeLocalization#25]
It may be useful to grab a string but in a different language without having to call `setLanguage` twice.
e.g.

`LocalizedStrings.getString(key, language);`

**Comment by stefalda** [comment]
Hi fender,
 you can already do so:

`strings.props[language][key]
`
if it's a needed feature I think there would no problem adding a clearer method.

Stefano

**Comment by stefalda** [comment]
I've added the method in the new version 0.13.
