### ISSUE TITLE
Nested Default/Fallbacks Keys Fail

### ISSUE THREAD

**Issue by nitsujri** [stefalda/ReactNativeLocalization#26]
Hi stefalda, 

Thanks for this great app that we're currently using. Our team decided to move to a single translation file to leverage PhraseApp.

Because of that, we use namespacing to keep things organized. This works great until we look at fall back.

    // Using 'it'; translations.homepage.mottoSmall; //fails
    {
      en: {
        homepage: {
          mottoSmall: "THIS IS A MOTTO SMALL",
          mottoLarge: "LARGE MOTTO",
        },
      },
      it: {
        homepage: {
          mottoLarge: "LARGE MOTTO IT",
        }
      }
    }

    // Using 'it'; translations.homepage.mottoSmall; // works
    {
      en: {
        homepage: {
          mottoSmall: "THIS IS A MOTTO SMALL",
          mottoLarge: "LARGE MOTTO",
        },
      },
    }

Fallbacks only work at 1 level deep (I'm sure that's how it was designed).

**Comment by stefalda** [comment]
Namespacing seems a great idea, originally I didn't think about it, now I've fixed the problem.
I'm glad this project is useful to you.
