### ISSUE TITLE
getInterfaceLanguage

### ISSUE THREAD

**Issue by limulidae** [stefalda/ReactNativeLocalization#29]
I am using zh_TW, but it returns zh only

zh could be zh_CN or zh_TW.

**Comment by ElvisChiang** [comment]
Have you tried master branch? I think it's fixed by last commit.

**Comment by stefalda** [comment]
Tonight I'll update npm version, till then you can use to install the lastest git version:

`npm install --save git+https://git@github.com/stefalda/ReactNativeLocalization.gi`

**Comment by stefalda** [comment]
I've updated the npm version, I close the issue. If it's still not fixed please reopen it.
