### ISSUE TITLE
The default language doesn't work

### ISSUE THREAD

**Issue by 77tb** [stefalda/ReactNativeLocalization#3]
Our project is now using ReactNativeLocalization. It supports English (en) and Simplified Chinese (zh-Hans).  When i changed the localization of my iPhone to Chinese, Traditional (Hang Kong) i found it doesn't display English nor Simplified Chinese.

After i carefully read LocalizedStrings.js i found `_getBestMatchingLanguage` didn't return the first item in `props` as it expected. In addition, in `setLanguage`:

var localizedStrings = this.props[language];

Should be this?

var localizedStrings = this.props[this.language];

or this ?

var localizedStrings = this.props[bestLanguage];

**Comment by stefalda** [comment]
The current interface language is displayed using 
```
var language = strings.getInterfaceLanguage();
```
and should return "zh-HK".
 
You could define strings as 
```
var strings = new  LocalizedStrings(var strings = new  LocalizedStrings({
  en:{
    hello:"Hello"
    },
  "zh-HK":{
    hello:"Hello from zh-HK"
  },
  it:{
    hello:"Ciao"
  }
});
```

In this way the default is English but if the interface is in Chinese it will use the "zh-HK" translation when you access the strings.hello variable.

There was an error in the _getBestMatchingLanguage method that didn't return the first language key but undefined, my fault.
I've fixed it now.

And you are right the right way to get the strings in the setLanguage method is
```
var localizedStrings = this.props[this.language];
```
even bestLanguage would be ok, they're the same at this point.

**Comment by 77tb** [comment]
It works, thx.
