### ISSUE TITLE
How to update text in multiple languages

### ISSUE THREAD

**Issue by arhmnsh** [stefalda/ReactNativeLocalization#36]
How can I update a key for all the languages, e.g.:

```
let strings = new LocalizedStrings({
  en:{
    city:"original city in en",
    area:"original area in en",
  },
  ar: {
    city:"original city in ar",  
    area:"original area in ar",
  }
});
```

Now, how to update a particular key, like city, in this.

**Comment by stefalda** [comment]
I don't understand what you're trying to achieve?
Changing the translation for a specific language at runtime?

**Comment by arhmnsh** [comment]
@stefalda yes buddy. Changing just a particular key on runtime.
Like I want to just update city.

**Comment by stefalda** [comment]
At the moment it's not possible, you could use something like 
`strings['city']='xxx'`

but it would change just the current language...

What's your use case? Because _immutability_ is the key to predictable results and it's heavily promoted for react apps...
