### ISSUE TITLE
How can I mock this component to make it work with jest?

### ISSUE THREAD

**Issue by sibelius** [stefalda/ReactNativeLocalization#37]

**Comment by carera** [comment]
+1 
I am just trying to write tests for my project, but both jest and mocha are complaining: 
```
Runtime Error
  - TypeError: Cannot read property 'language' of undefined
        at Object.<anonymous> (node_modules/react-native-localization/LocalizedStrings.js:17:35)
```

**Comment by stefalda** [comment]
I've tried to follow the JEST tutorial here [http://facebook.github.io/jest/docs/tutorial-react-native.html](http://facebook.github.io/jest/docs/tutorial-react-native.html), but I get a conflict with the required react version used by jest and react-native... so I'm unable to make any tests...

**Comment by sibelius** [comment]
I've used this as my current mock 

`__mocks__/react-native-localization.js`
```js
class RNLocalization {}

export default RNLocalization;
```

However this breaks for me, because my RNLocalization it is like this:

```js
const Localization = new LocalizedStrings({
  en:{
    scene: {
        title: 'title',
   },
  },
})
```

`Localization.scene.title` breaks.

I wonder if I could mock Localization instead of RNLocalization

**Comment by sibelius** [comment]
```js
const interfaceLanguage = 'en';

class RNLocalization {
  constructor(props) {
    this.props = props;
    this.setLanguage(interfaceLanguage);
  }

  setLanguage(interfaceLanguage) {
    const bestLanguage = interfaceLanguage;
    this.language = bestLanguage;
    //Associate the language object to the this object
    if (this.props[bestLanguage]) {
      //console.log("There are strings for the language:"+language);
      var localizedStrings = this.props[this.language];
      for (var key in localizedStrings) {
        //console.log("Checking property:"+key);
        if (localizedStrings.hasOwnProperty(key)) {
          //console.log("Associating property:"+key);
          this[key] = localizedStrings[key];
        }
      }
    }
  }
}

export default RNLocalization;
```

this works! \o/

**Comment by carera** [comment]
Thanks!

**Comment by CuongSmile** [comment]
can you support me finding the issue related to test?
 This is my test code 

```
test.js

import RNLocalization from '../../config/jest/react.native.localization'

it('should handle DO LOGIN SUCCESS WITH CORRECT USER INFO action ', () => {
  jest.setMock('react-native-localization', RNLocalization)
 // my code test
})
```
language/index.js
```
import LocalizedStrings from 'react-native-localization'

import vi from '../language/vi'
import en from '../language/en'

export default strings = new LocalizedStrings({
  en: vi,
  vi,
})
```

But alway got the error

TypeError: Cannot read property 'language' of undefined

      ```
at Object.<anonymous> (node_modules/react-native-localization/LocalizedStrings.js:21:35)
      at Object.<anonymous> (src/assets/language/index.js:1:176)
      at Object.<anonymous> (src/constants/error.message.js:1:223)
```

**Comment by ThaJay** [comment]
I have the same error:
`js
    TypeError: Cannot read property 'language' of undefined
      
      at Object.<anonymous> (node_modules/react-native-localization/LocalizedStrings.js:21:35)
`

but when I try and mock like so: `jest.mock('react-native-localization', () => RNLocalization)` using the example @sibelius gave above, I get the following error:
`js
    /tests/components/details.js: babel-plugin-jest-hoist: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
    Invalid variable access: RNLocalization
    Whitelisted objects: Array, Arra[...]17.
    Note: This is a precaution to guard against uninitialized mock variables. If it is ensured that the mock is required lazily, variable names prefixed with `mock` are permitted.
`

**Comment by ThaJay** [comment]
ok solved it:
You have to put the class literal into the mock.
```js
jest.mock('react-native-localization', () => class RNLocalization {
  language = 'en'

  constructor (props) {
    this.props = props
    this.setLanguage(this.language)
  }

  setLanguage (interfaceLanguage) {
    this.language = interfaceLanguage
    if (this.props[interfaceLanguage]) {
      var localizedStrings = this.props[this.language]
      for (var key in localizedStrings) {
        if (localizedStrings.hasOwnProperty(key)) this[key] = localizedStrings[key]
      }
    }
  }
})
```

**Comment by ardalahmet** [comment]
Thanks @ThaJay 
It worked.

I put it in a separate file for reusing in multiple tests.

Create a file named `react-native-localization-mock.js`:

```
export default class RNLocalization {
  _language = 'en';

  constructor(props) {
    this.props = props;
    this._setLanguage(this._language);
  }

  _setLanguage(interfaceLanguage) {
    this._language = interfaceLanguage;
    if (this.props[interfaceLanguage]) {
      const localizedStrings = this.props[this._language];
      for (const key in localizedStrings) {
        if (localizedStrings.hasOwnProperty(key)) {
          this[key] = localizedStrings[key];
        }
      }
    }
  }
}

```

In your test file:
```
//...

import mockRNLocalization from '../../data/i18n/react-native-localization-mock';

//...

jest.mock('react-native-localization', () => mockRNLocalization);

```

**Comment by arnsa** [comment]
Guys, this is still not working for me in any way :(. Could anybody help me out with this one? I copy-pasted the code, but even on the first property access (like I18n.home) I get an error: TypeError: Cannot read property 'home' of undefined.

**Comment by BrianJVarley** [comment]
@arnsa I'm having a similar error using this mock, here is my gist:

https://gist.github.com/BrianJVarley/9629f1ebc8969e7cf5fc7d1ce94c49e1

When I run a test with the mock mentioned by @ardalahmet I get the error:

```
TypeError: Cannot read property 'default' of undefined
      
      at null.user:/home/brian/Documents/Projects/test-app/node_modules/react-native-localization/lib/LocalizedStrings.js: (src/modules/settings/_specs_/SettingMenu.spec.js:21:86)
      at Object.<anonymous> (src/localization/appStrings.js:2:30)
      at Object.<anonymous> (src/modules/settings/SettingMenuView.js:14:17)
```

Any ideas what exactly is undefined in this case? The mock?

**Comment by BrianJVarley** [comment]
@arnsa  I got this mock working by instead creating a _mocks_ folder in the root beside the node_modules folder. 

The I let jest find the module from that folder, there is no need to import the mock into the test, in the spec I defined:

`jest.mock('react-native-localization');
`

See: https://jestjs.io/docs/en/manual-mocks#mocking-node-modules

**Comment by taranda** [comment]
I did this to get my initial test to pass.  It requires hardcoding the language:

```js
// __mocks__/react-native-localization.js

import LocalizedStringsCore from 'react-localization';

function getInterfaceLanguage() { return 'en-US'; } 

export default class LocalizedStrings extends LocalizedStringsCore{
  constructor(props){
    super(props, getInterfaceLanguage);
  }
}
```

**Comment by angelos3lex** [comment]
@BrianJVarley  did you find solution for this?

**Comment by stefalda** [comment]
@angelos3lex  have you tried to clean your node_modules folder and than perform a `npm i`?

Sometimes it helps...

**Comment by oferRounds** [comment]
Does anyone have a solution to this? Tried everything written here, but when running the test I still get:

> Test suite failed to run

>     TypeError: Cannot read property 'language' of undefined

> at Object.getInterfaceLanguage [as customLanguageInterface] (node_modules/react-native-> localization/lib/LocalizedStrings.js:49:23)
>       at LocalizedStrings (node_modules/localized-strings/lib/LocalizedStrings.js:65:42)
>       at new LocalizedStrings (node_modules/react-native-localization/lib/LocalizedStrings.js:63:117)

**Comment by taranda** [comment]
@oferRounds You have to mock the `getInterfaceLanguage()` function.  Are you doing that?

**Comment by oferRounds** [comment]
@taranda thanks – Yes, I tried both following syntaxes, but still the same error:

```
jest.mock('react-native-localization', () => {
  getInterfaceLanguage: jest.fn()
})
```

```
jest.mock('react-native-localization', () => {
  return {
    LocalizedStrings: {
      getInterfaceLanguage: () => String
    }
  }
});
```

**Comment by oferRounds** [comment]
This error started to happen when I upgraded to React Native 0.57

**Comment by oferRounds** [comment]
Maybe we need to add something like [this](https://github.com/1fabiopereira/react-native-i18n/commit/5f094a94128ce7e0986ef67c1e859d57871cef4d).

**Comment by taranda** [comment]
This is how I am mocking this:
```
// __mocks__/react-native-localization.js
import LocalizedStringsCore from 'react-localization';

function getInterfaceLanguage() {
  return 'en-US';
}

export default class LocalizedStrings extends LocalizedStringsCore {
  constructor(props) {
    super(props, getInterfaceLanguage);
  }
}
```

**Comment by FrancisLeigh** [comment]
For anyone Looking to mock the `formatString` method 
```javascript
const defaultInterfaceLanguage = 'en';

class RNLocalization {
  constructor(props) {
    this.props = props;
    this.setLanguage(defaultInterfaceLanguage);
  }

  setLanguage(interfaceLanguage) { ... }

  // eslint-disable-next-line class-methods-use-this
  formatString(string, formatObj) {
    function replacer(intpl = '') {
      const key = intpl.match(/[A-z]+/gm)[0];

      if (!(key in formatObj)) console.warn(`Key ${key} from ${intpl} not found in formatObj Object`);

      return formatObj[key] || intpl;
    }

    function interpolate(words) {
      const matches = words.match(/\{([A-z]*)}/gm);

      return matches.reduce((prev, curr) => prev.replace(curr, replacer), words);
    }
    return interpolate(string, formatObj);
  }
}

export default RNLocalization;
```

**Comment by vaibsshukla** [comment]
> Does anyone have a solution to this? Tried everything written here, but when running the test I still get:
> 
> > Test suite failed to run
> 
> > ```
> > TypeError: Cannot read property 'language' of undefined
> > ```
> 
> > at Object.getInterfaceLanguage [as customLanguageInterface] (node_modules/react-native-> localization/lib/LocalizedStrings.js:49:23)
> > at LocalizedStrings (node_modules/localized-strings/lib/LocalizedStrings.js:65:42)
> > at new LocalizedStrings (node_modules/react-native-localization/lib/LocalizedStrings.js:63:117)

Hi @oferRounds   can you please help me with this error. link which you have provided in consecutive thread is not currently working.
