### ISSUE TITLE
[question] how to get code completion

### ISSUE THREAD

**Issue by sibelius** [stefalda/ReactNativeLocalization#39]
Is there a way to make code completion work using rn-localization?

**Comment by stefalda** [comment]
I think it depends on your ide..
Someone has created typescript bindings and it Visual Studio Code it works.

<img width="488" alt="screen shot 2016-12-31 at 17 27 04" src="https://cloud.githubusercontent.com/assets/4984558/21578391/82766be2-cf7e-11e6-8acf-5d67d6df5287.png">
