### ISSUE TITLE
remove react-native from dependencies

### ISSUE THREAD

**Issue by agentS** [stefalda/ReactNativeLocalization#4]
In your package.json file you specifed `react-native` as dependency causing npm to install it twice. Having upgraded react-native to version 0.7.1 your dependency caused some serious issues making my application unexecutable. Having removed the dependency and deleted the react-native folder in your module's module folder solved this. So please remove this dependency, as your great project works fine without it too.

**Comment by stefalda** [comment]
Sorry, I'll change dependencies to peerDependencies as suggested here:
https://github.com/madebyform/react-parts#start-of-content

**Comment by agentS** [comment]
Great! Thanks a lot!

**Comment by isair** [comment]
+1

**Comment by Froelund** [comment]
+1

**Comment by stefalda** [comment]
Sorry for the delay.
I've fixed the problem.

**Comment by agentS** [comment]
No problem, thanks.
