### ISSUE TITLE
Android:  New Install Has Issue

### ISSUE THREAD

**Issue by xiaoneng** [stefalda/ReactNativeLocalization#44]
Steps taken:

1 .  install react-native-localization
2.   rnpm link react-native-localization
3.   Compile android successful and installed to device.

Error:

undefined is not an object ( evaluating 'localization.language' )

<unknown>
LocalizedStrings.js:  17

loadModuleImplementation
require.js: 122

**Comment by vectorjedi** [comment]
Just got the same error:
undefined is not an object (in Localized.Strings.js: 17)

I tried tracing back the error, but can not evaluate what caused the issue.
PLZ help!

**Comment by xiaoneng** [comment]
Seems new (RN 0.33+) with rnpm (1.9.0) link does not link correctly:

add:

new ReactNativeLocalizationPackage()

after:

new MainReactPackage()

in MainApplication.java and will work.
