### ISSUE TITLE
<Android> Changing localization does not work until app is restarted

### ISSUE THREAD

**Issue by bosung90** [stefalda/ReactNativeLocalization#47]
Happens only in Android as iOS kills any application when language is changed.
Steps to reproduce:
1. Run the application
2. Put the app in the background, change the language.
3. Go back to the application.
4. Notice that localization is still the old one, even after you re-render the page by detecting app resume using `AppState`.

I have noticed that in your `LocalizedStrings.js` file you retrieve the language using
`require('react-native').NativeModules.ReactLocalization.language.replace(/_/g,'-')`
So I tried putting this inside the constructor instead and ensured new instance of LocalizedStrings is used everytime my application resumes from paused state. 
However, this will still give me the old localized string, indicating that localization in the native side is cached. 
I also tried to use `require('react-native').NativeModules.ReactLocalization.getLanguage((language)=> {
})`

However `language` is `null`.

Correct localization is retrieved after app is restarted, which is not ideal.

Let me know if there is a workaround for this.

Thanks!

**Comment by stefalda** [comment]
Hi, 
I think you should subscribe to some system notifications events like suggested here http://stackoverflow.com/questions/8049207/how-to-refresh-activity-after-changing-language-locale-inside-application and reload the language strings...

**Comment by bosung90** [comment]
I was hoping to solve this without having to create any native bridge but maybe I have to.
I will come back to this issue later as there are other more important features to implement.
Thank you for the suggestion!

**Comment by MaxToyberman** [comment]
@bosung90  did you find an elegant solution to this ?

**Comment by MaxToyberman** [comment]
you can use this to detect language change and then restart the layout:
https://github.com/MaxToyberman/react-native-locale/blob/master/README.md

**Comment by Donhv** [comment]
same issue.
Have any solution with this lib?

**Comment by Biplovkumar** [comment]
same here
