### ISSUE TITLE
Provide an xcode project with a library target

### ISSUE THREAD

**Issue by isair** [stefalda/ReactNativeLocalization#5]
Most react-native npm packages do this; eases and standardizes the installation process. Some examples: [react-native-video](https://github.com/brentvatne/react-native-video), [react-native-linear-gradient](https://github.com/brentvatne/react-native-linear-gradient), [react-native-activity-view](https://github.com/naoufal/react-native-activity-view).

**Comment by jhabdas** [comment]
+1 Having this will allow the Obj-C header and implementation files to be organized under *Libraries* so it's clear they're not part of the application source code. Not having this will make it more likely users may customize the module and make future upgrades more difficult in the implementing apps.

**Comment by stefalda** [comment]
Thank you guys, it's a great suggestion... I've just implemented it.

**Comment by jhabdas** [comment]
Was able to pull down `0.1.7` and include the module in my *Libraries* folder. Lookin' good @stefalda!
