### ISSUE TITLE
Do you cache?

### ISSUE THREAD

**Issue by scazzy** [stefalda/ReactNativeLocalization#51]
!This is not an issue.

Does this lib have caching implemented? Native or Javascript? So it's a smooth experience across the app once the app opens and while you're switching between Scenes/Screens/Activities.
If not, can you drop some info on the performance?

**Comment by stefalda** [comment]
Hi,
 using the singleton pattern, putting the strings in a separated file required by others and loading it once, I think the performance are ok, but I've not made specific tests.
