### ISSUE TITLE
IOS, cant run.

### ISSUE THREAD

**Issue by IvRRimum** [stefalda/ReactNativeLocalization#54]
Trying to deploy on Iphone 6 now, i get nasty error:
<img width="382" alt="screen shot 2016-12-22 at 19 12 36" src="https://cloud.githubusercontent.com/assets/5957079/21433795/e4c5af12-c879-11e6-8f13-357f03a6d565.png">

I tryed to reinstall with `rnpm install` ... command, still no luck.

**Comment by stefalda** [comment]
Hello, 
 it seems like rnpm is no more, it's been merged to the react-native-cli... but the suggested way to install with react-native-cli doesn't seem to work (at least for me)...

However this code works:

```
npm install react-native-localization --save
react-native link
```

Hope this helps...
