### ISSUE TITLE
ios error in v.0.1.24

### ISSUE THREAD

**Issue by sectorf8** [stefalda/ReactNativeLocalization#55]
v0.1.22 works fine but v0.1.24 get this error:
ReactLocalization.m:37:63
"property 'languageCode' not found on object of type 'NSLocale *'

**Comment by stefalda** [comment]
Maybe it's a new iOS 10 property. What version of iOS are you deploying to? I'll add a check...

**Comment by fabianbormann** [comment]
I have a similar problem: The debugger stops also to line 37 of ReactLocalization.m

```return [NSString stringWithFormat:@"%@-%@", currentLocale.languageCode, currentLocale.countryCode];```

with:

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFLocale languageCode]: unrecognized selector sent to instance 0x15e2c9f0'

Error occurred only when I deploy to my device (iPhone 4 iOS 9.3.5) everything works fine in iPhone6s emulator. 

Thank you for help :)

**Comment by fabianbormann** [comment]
Ok .. The error is gone after changing:

```swift
    return [NSString stringWithFormat:@"%@-%@", currentLocale.languageCode, currentLocale.countryCode];
    // return [[NSLocale preferredLanguages] objectAtIndex:0];
```

back to 

```swift
    // return [NSString stringWithFormat:@"%@-%@", currentLocale.languageCode, currentLocale.countryCode];
    return [[NSLocale preferredLanguages] objectAtIndex:0];
```

**Comment by stefalda** [comment]
Fixed in 0.25...

**Comment by mhdayyoob** [comment]
still the Issue there https://cloud.githubusercontent.com/assets/16235674/24788108/932069e6-1b20-11e7-99c2-bf1add49981b.png

**Comment by stefalda** [comment]
That's strange... what version of iOS are you targeting?

**Comment by mhdayyoob** [comment]
Iam targeting on iOS 10
