### ISSUE TITLE
Localization not working for en-US/UK/etc.

### ISSUE THREAD

**Issue by kevinhylant** [stefalda/ReactNativeLocalization#56]
When first integrating your library at version 0.1.22 in October, localization worked flawlessly (eg en-US, en-UK, etc). Thank you for that!

But for some reason, at some time in the past month, it no longer is setting the appropriate language for localization purposes, it simply seems to set the language based on the lowest-indexed `en-` key in the localizedStrings dictionary which is provided on initialization.

For instance, the following works properly for `it`, but always sets the language to `en` even when the application language is English (US).

```
import LocalizedStrings from 'react-native-localization'

const localizedStrings = new LocalizedStrings({
    'en': {
        bookmarkButtonActive: 'Favourited',
        bookmarkButtonInactive: 'Favourite',
    },
    'en-US': {
        bookmarkButtonActive: 'Favorited',
        bookmarkButtonInactive: 'Favorite',
    },
    'it': {
        bookmarkButtonActive: 'Italianoed',
        bookmarkButtonInactive: 'Italiano',
    },
})

export default localizedStrings
```

I have tried upgrading to the latest 0.1.25, but still seeing the same issue. It does, however, work properly for internationalization... perhaps something broke in one of your downstream localization deps? Haven't had a chance to debug the source code yet.

### Application Scheme
![image](https://cloud.githubusercontent.com/assets/7389576/22066645/e2ee993c-dd5b-11e6-9aa7-92c636f568f8.png)

**Comment by stefalda** [comment]
Hi, I've just made your same tests and everything seems to work as expected...

**Comment by kevinhylant** [comment]
I forgot to update this Issue. This self-resolved when I upgraded my version of RN & React. Thanks!

I will provide more information about my versions in future Issues.
