### ISSUE TITLE
Something went wrong initialing the ReactLocalization module.

### ISSUE THREAD

**Issue by marcw** [stefalda/ReactNativeLocalization#61]
Hi, I created a React-Native project yesterday, and I just installed your library.

I ran the installation commands as specified:
```
npm install react-native-localization --save
react-native link
```

My application in the simulator now displays this error:
![capture d ecran 2017-02-03 12 00 27](https://cloud.githubusercontent.com/assets/160332/22588972/5d8934f0-ea08-11e6-9aaf-71ca51f8c55b.png)

I killed the simulator, killed the terminal launched by ``react-native run-ios`` and reran `react-native run-ios`` but I still got the error. 

Any help would be appreciated, thanks :)

**Comment by patricktresp** [comment]
Same Issue here - rn0.40.
missing valid libReactNativeLocalization.a

**Comment by stefalda** [comment]
Just close all the terminal windows and restart the packager... I've just tested this way, and it works...

**Comment by stefalda** [comment]
Hi,
 I've just created a new project with the current version of react native:  0.41.2 using the react-native-cli 2.0.1, installed the library, quitted all the terminal windows and it worked...

**Comment by patricktresp** [comment]
Hey, 
using 

react-native-cli: 1.0.0
react-native: 0.40.0

and it will not work as you mentioned.
I will try to update cli, but this should'nt have any effect on the module?

**Comment by stefalda** [comment]
as a matter of fact, no... the library should work even with version 0.40...

**Comment by patricktresp** [comment]
ok, updating to cli2.0.1 did not make it happen.

Which Version are you using, git or npm ?

**Comment by stefalda** [comment]
npm 3.8.9

**Comment by patricktresp** [comment]
hmm
- restart machine
- rm node_modules
- re-linkung 
- restart machine

will not get me to localization heaven…
<img width="570" alt="06 02 2017 22 51 07xcode" src="https://cloud.githubusercontent.com/assets/1619156/22667851/cb0887b6-ecbe-11e6-944a-9b31dc2e4fd2.png">
This is iOS only error, but as i mentioned . the **libReactNativeLocalization.a** is not found on computer, therefore it can't lead to success.

you probably have that on your device, therefore linking is successful?

**Comment by stefalda** [comment]
No because it's bundled with every app...
Is cocoapods updated on your machine?
`pod --version
`
gives me version 1.2.0

Try to compile the library project (ReactNativeLocalization.xcodeproj) located in node_modules/react-native-localization  from XCode...

**Comment by patricktresp** [comment]
Hey thanks so far! I Really appreciate that
Now it won't compile because of this error now:

".../node_modules/react-native-localization/ReactLocalization.m:39:67: Property 'languageCode' not found on object of type 'NSLocale *'

using xcode Version 7.3.1
pod version 1.2.0

<img width="857" alt="07 02 2017 06 18 13google chromegithub com" src="https://cloud.githubusercontent.com/assets/1619156/22678813/387444b4-ecfd-11e6-9ef2-bb566984cd92.png">

hmm what now? Do you have any clues?

**Comment by patricktresp** [comment]
I guess its an Xcode 7.* Issue?

**Comment by patricktresp** [comment]
I updated Xcode to 8.x 
Now i can compile the node_modules/react-native-localization Project, but still i do get the initial error.
Now i am somehow stuck w/ this.

**Comment by stefalda** [comment]
Try to clean the project build from XCode and start everything from the terminal... I guess there's some problem with the way the  library has been added to the RN project (by XCode or cocoapods)

**Comment by marcw** [comment]
Thanks for your input, @stefalda. I had a compilation error while building the project (due to a removed dependency that wasn't totally removed from the `project.pbxproj` file). I removed it, cleaned the `build` folder and recompiled the project. Everything is fine now.

**Comment by patricktresp** [comment]
Unfortunatly nothing helped to get over this.
removed linkages in xcode project - cleaned, new install, cleaned build path, restarted.
I guess i will need to implement something custom :(

**Comment by SoorajChandran** [comment]
Same issue for me when converting an existing react-native project to expo.io project. Any solutions yet?

**Comment by stefalda** [comment]
You cannot use external library in expo.io project...

> Because you don't build any native code when using Create React Native App to create a project, it's not possible to include custom native modules beyond the React Native APIs and components that are available in the Expo client app.

**Comment by EskelCz** [comment]
I've ran into the same issue with a vanilla RN project. The solution was to add ReactNativeLocalization.xcodeproj into the project and also to the "Link Binary with Libraries" list.
Hope it helps.

**Comment by Raulif** [comment]
@EskelCz your solution helped me! Somehow it was missing on the "Link Binary with Libraries" list. 👍

**Comment by shubhamkes** [comment]
Solved using
`rm -rf node_modules()` {may be first two option can be skipped, i didnt check though}
'npm i`
`cd ios`
`pod install`
`cd ..`
`npm start`
