### ISSUE TITLE
dont run on Android and RN-0.40 . pls help

### ISSUE THREAD

**Issue by Mactub07** [stefalda/ReactNativeLocalization#62]
A problem occurred configuring project ':ReactNativeLocalization'.
> failed to find Build Tools revision 23.0.1

**Comment by ElvisChiang** [comment]
just install android sdk build tool 23.0.1

**Comment by MonsJovis** [comment]
There is a mistake in the README. The compile project instruction in `android/app/build.gradle` should be like the following:

```
...
dependencies {
    ...
    compile project(':react-native-localization')
}
```

**Comment by stefalda** [comment]
Thanks @MonsJovis
