### ISSUE TITLE
[question] How can i add translations dynamically?

### ISSUE THREAD

**Issue by SerzN1** [stefalda/ReactNativeLocalization#63]
Hello. Any ideas how can i do this?

**Comment by MagicalYan** [comment]
`constructor() {
        super();
        this.state = {
            tempString: '?????'
        }
    }

    setStrings(key) {
      let strings = new LocalizedStrings({
        en: {
          how:"How do you want your egg today?" + this.state.tempString,
          boiledEgg:"Boiled egg",
          softBoiledEgg:"Soft-boiled egg",
          choice:"How to choose the egg"
        },
        zh: {
          how:"你好啊" + this.state.tempString,
          boiledEgg:"Boiled egg",
          softBoiledEgg:"Soft-boiled egg",
          choice:"How to choose the egg"
        },
        it: {
          how:"Come vuoi il tuo uovo oggi?",
          boiledEgg:"Uovo sodo",
          softBoiledEgg:"Uovo alla coque",
          choice:"Come scegliere l'uovo"
        }
      });
      return strings[key];
    }`
@SerzN1 Maybe this is useful.
