### ISSUE TITLE
Should there be a default value returned when the key does not exist ?

### ISSUE THREAD

**Issue by aimak** [stefalda/ReactNativeLocalization#65]
Hello,

Coming from the iOS world, when a localized string does not exist, we get the `key` itself as default value. I was wondering if this kind of feature would be considered/accepted in the `ReactNativeLocalization` library ?

Basically, in https://github.com/stefalda/ReactNativeLocalization/issues/23 example, 

```
import LocalizedStrings from 'react-native-localization';
let strings = new LocalizedStrings({
  en:{
    how:"How do you want your egg today?",
    boiledEgg:"Boiled egg",
    softBoiledEgg:"Soft-boiled egg",
    // choice:"How to choose the egg" remove choice here as well
  },
  it: {
    how:"Come vuoi il tuo uovo oggi?",
    boiledEgg:"Uovo sodo",
    softBoiledEgg:"Uovo alla coque",
   // notice missing 'choice'
  }
});
```

`strings.choice` would print `choice` because it could not have been found.

**Comment by stefalda** [comment]
I think It could be a good way to be notified of missing keys...

**Comment by Stgltz** [comment]
this would be useful if the string value has come from an updated database that doesn't yet have a translation in the dictionary.

**Comment by stefalda** [comment]
it's not possible to do so at invocation time... missing translations are logged, but they have to be declared at least in the default language...
