### ISSUE TITLE
A label based object definition (instead of a langage based)

### ISSUE THREAD

**Issue by olivierlesnicki** [stefalda/ReactNativeLocalization#7]
Currently the structure to create a LocalizedString object is the following:
```
langage: {
  label: 'value'
},
langage-2: {
  label: 'value'
}
```
But as a develop is more likely that i'll delete and edit labels instead of deleting/editing languages. To fix this inefficiency I'd recommend allowing devs to define LocalizedString using the following format:
```
label: {
  langage-1: 'value',
  langage-2: 'value'
}
```

**Comment by jhabdas** [comment]
This feels more of a preference than an issue. Personally I'd rather see all like languages grouped together. Please consider closing.

**Comment by stefalda** [comment]
Personally I prefer having all language labels together instead of repeating the language within each labels, anyway it's doable but let's see what other thinks about it.

**Comment by jhabdas** [comment]
As country and variant is added to the locale identifiers it'll lead to
duplication in the key-value pairs either way. Thinking of a way to specify
multiple locales for a single string literal feels more DRY. The case
statement comes to mind as a solution but would likely require the current
organization pattern. Of course both approaches can be done outside this
wonderful library.

FYI I started your Wiki
