### ISSUE TITLE
getLanguage() method do not work?

### ISSUE THREAD

**Issue by xuho** [stefalda/ReactNativeLocalization#70]
I want to get current language and i'm using: LocalizedStrings.getLanguage() but it show an error: undefined is not funtion?
How to fix it?
Thank.

**Comment by stefalda** [comment]
Hi,
you should reference your local instance.

strings.getLanguage()

**Comment by xerotolerant** [comment]
Where is this local instance defined? I don't understand...

**Comment by stefalda** [comment]
When you instantiate the Library like this:
```
strings = new LocalizedStrings(options);
strings.getLanguage();
```

**Comment by xerotolerant** [comment]
Thanks, idk how I missed that.
