### ISSUE TITLE
Add support in test

### ISSUE THREAD

**Issue by vlivanov** [stefalda/ReactNativeLocalization#72]
Hello! I am trying to test some of my js classes dependent on LocalizedStrings and I fail to do so. 
I got the following output: 

>  TypeError: Cannot read property 'language' of undefined
      
      at Object.<anonymous> (node_modules/react-native-localization/LocalizedStrings.js:21:35)
      at Object.<anonymous> (js/DemoTest.js:1:214)
      at Object.<anonymous> (__tests__/model/loctest.js:1:104)

Here is the DemoTest.js: 

`import LocalizedStrings from 'react-native-localization';

const i18n = new LocalizedStrings({
    de: {
        active: 'active',
    }
});

export const checkMyLocalization = () => {
    console.log('Active = ' + i18n.de.active);
};`

And loctest.js:

`
import { checkMyLocalization } from '../../js/DemoTest';

test('Loc result', () => {
    checkMyLocalization();
});
`

What am I supposed to do to make the test work?

**Comment by vlivanov** [comment]
Duplicates #37

**Comment by CuongSmile** [comment]
can you share with me about your test code?

**Comment by vladimir-ivanov-epam** [comment]
@CuongSmile here you are:

![image](https://user-images.githubusercontent.com/26428449/26966681-caea0a70-4d03-11e7-9fe4-2a23a9068966.png)


This is basically everything I did to get my tests work

**Comment by CuongSmile** [comment]
Did you add the path to file  in setupFiles at package.json ?. it same 
```
"jest": {
    "preset": "react-native",
    "setupFiles": [
      "./config/jest/mock.fetch.js",
      "./config/jest/react-native-localization.js"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|react-navigation|rn-textinputlayout)"
    ]
  }
```

**Comment by vladimir-ivanov-epam** [comment]
Nope, nothing like that. Just __mocks__ folder in js folder.

**Comment by CuongSmile** [comment]
@vladimir-ivanov-epam  Ok many thanks
