### ISSUE TITLE
Native module ReactNativeLocalization tried to override

### ISSUE THREAD

**Issue by ye4ever** [stefalda/ReactNativeLocalization#75]
hi, 
how i can solve this ??
Native module ReactNativeLocalization tried to override ReactNativeLocalization for module name ReactLocalization. If this was your intention, return true from ReactNativeLocalization#canOverrideExistingModule()

**Comment by stefalda** [comment]
Hi @ye4ever, where are you reading this error?
I've never seen it...

Stefano

**Comment by ye4ever** [comment]
When i run the app by command or android studio it showen  in the device

**Comment by stefalda** [comment]
Here h[ttps://github.com/oney/react-native-gcm-android/issues/35 ](https://github.com/oney/react-native-gcm-android/issues/35 )they say that this could happen if you add the same module more than once in the Android project...

Take a look at it...

**Comment by farruxx** [comment]
@ye4ever Check your modules list in Activity or Application. It might be added twice 
` @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ReactNativeLocalizationPackage(),
            new ReactNativeLocalizationPackage(),`
