### ISSUE TITLE
Support country and variant in locale identifiers

### ISSUE THREAD

**Issue by jhabdas** [stefalda/ReactNativeLocalization#8]
iOS supports a [number of locales](https://gist.github.com/pjc-is/49971b36db38fdeae6fc). Most locale identifiers use `_` to separate *language*, *country* and locale *variant*.

As of now I'm unable to use this module to specify anything beyond the *language*, which becomes problematic for localizations where different countries or localities speak the same language or variants of a language thereof.

**Reproducing this issue:**

Force the locale in Xcode:
```objective-c
  [[NSUserDefaults standardUserDefaults] setObject:[NSArray arrayWithObjects:@"zh_Hans", nil] forKey:@"AppleLanguages"];
```

Run the project and access the key:

```js
let localizedStatus = new LocalizedStrings({
  en: {
    playing: "Now playing commercial-free!",
    paused: "Tap above to continue listening.",
    stopped: "Tap above to tune in.",
    buffering: "Buffering... Hang tight.",
    error: "Long-press above to restart stream.",
    disconnected: "Connect to the Internet to listen."
  },
  zh_Hans: {
    playing: "现正播放无广告时段！",
    paused: "按上面来继续收听。",
    stopped: "按上面来切换电台。",
    buffering: "正在缓冲...请稍候。",
    error: "长按上面来重新开始播放。",
    disconnected: "收听电台需要连接到因特网。"
  }
});
```

The actual result is English is output. The expected result is that Simplified Han is output. The same issue occurs for `en_US` and `en_GB` locales. As a workaround I've chopped off the *country* and *variant* parts of the locale identifier, leaving only the language, i.e. `zh`.

**Comment by stefalda** [comment]
I'm aware of the issue. I just chose simplicity other country specific languages but I'd be happy to revise the code in a few weeks (currently I'm without my laptop)

**Comment by jhabdas** [comment]
Sorry to hear that. Happy to test any code snippets you pass and sub a PR

**Comment by stefalda** [comment]
Hi Josh, I've come back home today and make some tests...

iOS actually returns the language in the following format:
en-AU
en-GB

so you should write something like 
```JS
var strings = new  LocalizedStrings({
  "en-AU":{
    how:"How do you want your egg today AU?"
}
});

or, in your case: 
  "zh-Hans"

Let me know if this solves your problem...

**Comment by jhabdas** [comment]
Sweet business! Thanks. I'll report back soon.

**Comment by stefalda** [comment]
Here's a list of known returned iso codes:

http://www.ibabbleon.com/iOS-Language-Codes-ISO-639.html

**Comment by jhabdas** [comment]
Looking good. [Documented](https://github.com/stefalda/ReactNativeLocalization/wiki#use-country-and-variant-in-locale-identifiers) in Wiki.
