### ISSUE TITLE
Something went wrong initialing the ReactLocalization module in Android.

### ISSUE THREAD

**Issue by binita12345** [stefalda/ReactNativeLocalization#84]
I created react-native project and install Library for Localization using following command.

 **"npm install react-native-localization --save"**    

and run the project using "**react-native run-android**" command and getting following error.
![react-error](https://user-images.githubusercontent.com/23699891/28654141-9db89090-72af-11e7-9ee4-e8361afefce2.png)

I have used following packages in my project.
    "native-base": "^2.3.0",
    "react": "16.0.0-alpha.12",
    "react-localization": "^0.1.1",
    "react-native": "0.45.1",
    "react-native-localization": "^0.1.31",
    "react-native-vector-icons": "^4.2.0"

And when I run **"react-native link"** command, getting this error.

![image](https://user-images.githubusercontent.com/23699891/28654478-3b0d3218-72b2-11e7-8d68-f9bb5a740e30.jpg)

Please give me solution as soon as possible.

**Comment by flieks** [comment]
@binita12345 i'm having the same issue. Did you find a solution ? 
Using Expo

**Comment by stefalda** [comment]
Hi, it's not possible to use external plugins with Expo projects...

**Comment by EskelCz** [comment]
What fixed it for me was to add ReactNativeLocalization.xcodeproj into the xcode project and also to the "Link Binary with Libraries" list.

**Comment by Raulif** [comment]
@EskelCz your solution helped me! Somehow it was missing on the "Link Binary with Libraries" list. 👍
