### ISSUE TITLE
something went wrong initializing the native ReactLocalization

### ISSUE THREAD

**Issue by Dr-MHQ** [stefalda/ReactNativeLocalization#91]
I simply created an empty app via Expo, install the package, linked then installed again

once I import the package into the project I get this error message

![image](https://user-images.githubusercontent.com/2570175/29920314-a2deb768-8e55-11e7-9cdb-adf66b22147f.png)

Expo is showing this:

Warning: 'react-native-localization' dependency is not installed.

I have tried 2 projects once with NPM 5 and the other via Yarn 0.27.5

**Comment by vishu-daffodil** [comment]
I am facing the same issue. I also added a screenshot of debugger.
![screen shot 2017-08-31 at 5 01 56 pm](https://user-images.githubusercontent.com/28556826/29921160-3b28055c-8e6e-11e7-8bf8-05a413280878.png)

**Comment by stefalda** [comment]
Expo apps don't support additional plugins!
You should have a STANDARD RN App...

**Comment by Dr-MHQ** [comment]
just created a standard app and faced the exact same issue

**Comment by ociata** [comment]
I think this is more issue of a Jest rather than ReactNativeLocalization, but did anyone find solution to this?

**Comment by EskelCz** [comment]
What fixed it for me was to add ReactNativeLocalization.xcodeproj into the xcode project and also to the "Link Binary with Libraries" list.
