### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by marcusvbp** [stefalda/ReactNativeLocalization#99]
Hi!

I can't use this lib on Android.

step-by-step install and usage:

1 - npm install --save react-native-localization
2 - react-native link react-native-localization

At this moment, the app works like a charm.

3 - look this gist: https://gist.github.com/marcusvbp/6e170aa53b86d1f94667d8324669f632
if I uncomment the line 8 (import LocalizedStrings from 'react-native-localization';) the App crashes with the error:

![image](https://user-images.githubusercontent.com/4376611/31502367-3c8898da-af43-11e7-9833-ba253a9a9e36.png)

More infos:
- react-native-cli ver: 2.0.1

- package.json:

> {
>   "name": "AppAgora2030",
>   "version": "0.0.1",
>   "private": true,
>   "scripts": {
>     "start": "node node_modules/react-native/local-cli/cli.js start",
>     "test": "jest"
>   },
>   "dependencies": {
>     "axios": "^0.16.2",
>     "i18n-js": "github:fnando/i18n-js#v3.0.1",
>     "native-base": "^2.3.1",
>     "react": "16.0.0-alpha.12",
>     "react-native": "0.48.3",
>     "react-native-collapsible": "^0.9.0",
>     "react-native-datepicker-dialog": "0.0.6",
>     "react-native-extended-stylesheet": "^0.6.0",
>     "react-native-localization": "^0.2.1",
>     "react-native-looped-carousel": "^0.1.7",
>     "react-native-modal": "^4.0.0",
>     "react-native-popover": "^0.2.0",
>     "react-native-progress": "^3.4.0",
>     "react-native-vector-icons": "^4.4.2",
>     "react-native-youtube": "^1.0.0",
>     "react-navigation": "^1.0.0-beta.11",
>     "react-redux": "^5.0.6",
>     "redux": "^3.7.2",
>     "redux-thunk": "^2.2.0"
>   },
>   "devDependencies": {
>     "babel-jest": "21.0.2",
>     "babel-preset-react-native": "3.0.2",
>     "jest": "21.0.2",
>     "react-test-renderer": "16.0.0-alpha.12"
>   },
>   "jest": {
>     "preset": "react-native"
>   }
> }

**Comment by nes123** [comment]
I am having the same problem. Did you find a solution ?

**Comment by miriyas** [comment]
same

**Comment by nes123** [comment]
did you find any alternative to this package ?

**Comment by miriyas** [comment]
https://github.com/AlexanderZaytsev/react-native-i18n/issues/134
I stuck there, and I installed this package for workaround, but I stucked here.

I got problem only Android project, iOS is well working.
I think something is wrong with linking, maybe related to RN version..
RN 0.49.3, React 16.0.0

**Comment by marcusvbp** [comment]
I am using the react-native-i18n now and it's working very well

@miriyas I got this issue too but it's gone after I reinstall the package

**Comment by miriyas** [comment]
@marcusvbp Yeah I reinstalled about 39 times but no luck.
Now I am digging inside and comparing linking method of react-native-navigation with this.
I am new to Java, but doing anything for this fixed..

**Comment by stefalda** [comment]
I've to update to check the problem, but just to be sure... 
how did  you create your app?

Because if you've used the `Create React Native app` shortcut you should `eject the app as detailed here  [here](https://facebook.github.io/react-native/docs/getting-started.html#caveats).

**Comment by miriyas** [comment]
@stefalda hi, I made without CRNA, thanks.

**Comment by clecotechAish** [comment]
Is it still not working on android?

**Comment by stefalda** [comment]
No plugin works if you don't eject the React Native created app...
It always worked with Android...

**Comment by clecotechAish** [comment]
I created the app using react-native init
It is always giving me error : 
`Something went wrong initialing the ReactLocalization module. Did you forgot to run react-native link. 
`

**Comment by sangyakhare** [comment]
Same issue here. On iOS it is running fine. Error occurs on Android. Tried manual linking as well. Nothing works. And I created the app with React Native cli.
